sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=mvsorg/mvs-explorer-api-v2
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$TAG .
    - docker push $REPO
env:
  global:
  - secure: ZBDStifM9SlGaoa07GOkEyEgHC7bceTH2IUrhmCz1x+yT3Q6AP4J2yEmd8bwGzo3I+0MUdRMTTPw/oTcT4gu6mlMzCu3MuGjPiJVCk1YslgqH5dJQ3EgXiKMUgUNNgV8aT6ajk31jC6WnydkvLC5Hd3dQjSvbxiz7fEFRj+CbU3MKYwAkjNgvlxzO5vpTGXvJu3OBEzE3YEIL1ezLwhQPOZBxaurE/eVWyTGZcr79isaqcvpZZRbdIMFPxnofUPi7pCBIaJmVghNQ08IjI6Z89hv5CWsWLc/1GRPZCBesTT0i6mIZUuYVKQJScP33SW14ej49mEoh3U1J/JIVUe+mpZkaErWVFhaRqSH7fWh5IgL2DmJiYA3U5oNfFLaOEk1/BoF6e44DnE/KxRwxl67camGdal6iKQ9Df5aAMGLfSSMUEEKHBIyrAc4z1FJ0ELiFCQz3yRjALy2Lckf56JiCb6W0qKyNR/W9Cuvfm2waDrNkwKbSfMrd4ZH4Pdj9g+AtABA3iuzl0llQsWOM9OGhsKPeanZV+wxesIym1DdIDiwVCu0RyXWTI6XVXuljtjK1/vM/eb7M2mQPVNbcExWqP0n7xfW04bzlPi1EbkU4pUUNVPbSuljqpN6KcNMgu0lc1dlMxB4iohBQRxBO34QD4UqKbxuCuVCdaxv/9BR+sQ=
  - secure: XkexR4VCdx04CljQcJonIVUg9XtJADz5looY0vRRH2fVb8OaIhnAezxHvzCDBYn8uobp8lXZD11xHFWXE+h5shdfxJ2OQx/29DQkOamqbxdiiGUPL8og8SuSfiBkEgKYVcts9DaS75wuoCvwAMDPjlnnes8ZF0bvKS87/0ZJNG+gSTRdD9S1KL2AfQa7AlVRE+7ZxS3kCvwU0V2/ddKnNu1WLTVsOW6dSifiCK4hhSE9rwIQ13oGY4ZQg2lzlRy6gsAfuVkddh0f61bLTL+rbP1SnE9PRnS7m6a/Bv15Xhr2DXClMs+Db0496cDBa6M6actGvn3y6kWB+w6msvYUvpezGM6xS75W/saiQr0RFt5Y4qRNMvb0PtOG63RLXuO5N1vKH427FaneEw40Bj2l2VDWK7668pnxBziWJhLD3wLuungnZ62wG8eJOInSBhhDCtHBoyjCg878hK66Xa1RqqYOkmuT1pJDlQyj9FChLgEKvkL7kY8BndPGLPXhZHJm+/ymSvh9s6fSgMJ/YJjhilOIwFSzYmOHaA+fxo6NiZuBp2FHBA9IuFHAHviCX/MNvWoNzTxokwtU05yvN5wuwFXoeTrLR7lb5IYK2JbuJoQf9BZEOkN0lnn08bLkI3w1gi0mL44YcLpfy5MvOxqoxG96WkDrJi5wjEJG+SqJ+mU=
