sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=mvsorg/mvs-explorer-api-v2
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$TAG .
    - docker push $REPO
env:
  global:
  - secure: GkwuF2VR8coWjMnKsg+m1J7PjJlek+kwXRTohUSfEtyxeT8W6Ks7AEFPbs/9wR+499acw7/4grYGDg73cWM1A4OmZpIDqDCmaplEwZ/I5iJeqDr9/+9AMCggz9stkmNsg7SAk1wqCOVjLJYXhk04LrkWKp5pJxsNao9wibYsJYCe8S60f2ohAjCF7EghgO9+2GTjamETNHns2LQUyOloaA8B5Iix+q8Zg4vyxDZWVnDe0cUlRw5QtnhYFBNcB1vhAw7Y+P2hqnyVTPWsjJ43iOUSen9rSkX34fmVmqDTUvmJaU4BJgIYT4rdTr01SXqJWlZZiiL6ZhQUI9pTQEtrQn+60tn2DJzKY9hKSYoZ4bQHiUFcSnhkFbWb5747cbOx0kDUhoJN3jaSz1ICwHpbmHNhe4d96abMxclRYH0XcbtZUDqEIGx13qNkpsMgY7dV118P1hQCuXxfKyjw4L7QMtlOCONXOcBbnC3E10BeEUAf4VADaIJEGHClrzLnViGhn5LX2KCjjyl+vS4HfDG+/wghv5ygiAtx1RnK4PcwAHe/2jeSQQ4MNJiu9ljIfB+B+V/fzRih1KF9upw3E5HelTwPXMMZg6GyAkIFtx4KvdWcenitHZ6BKMjhU3WhZ7Em3I4E+JLy86/D+ix3g2gWfx/jSBFacw8liXdsyzTldqw=
  - secure: zTMj0IXcIE+1WoIgK91am7HcYamBoLw4sr+jDZ0WRjt9bOxx5vLg8EpiUklyIuPUFNWY+UIhx0KqDC3QeiHMJnHVrkmJa9MBil1vd9qyMtByoThYjJkVPuYOZR1JwNH1seh0/GfHgJEfYZIXMZ7bj4uDpRfOCek5pdA7dDQBz/OMosfGgLyegqqDLC0hrx5E0q/yJ0RFfPipKNpNEOSxF3zzN+rd/1N5GgrAkynRrOeYf0zxWTTBGcD/e4lE94yRWdX8cgx2cUE+P7jW9eYJa3sJwE0p82h5foMJ16i5bPNA/fGXo1VYkJeCCp9Y7U1ZZTAbi6Wojg00f8TYy278m7cw9oaqb5Lh4xtDb1FqYqBNG0uI5A/zUr5kgausU+PoxVzCjaeRpH/1BXBQp+sBh2KNsTnEN30kA8t+EIqXe/t+8+05NgERamLV7FlyFy6mWK35YwiEOhmyVsv+s09e7w07YHBcni5MaLL7a6F7j4ym1Dnf/xZaJqDvUZRCH36PIZE0QPVqiHvBYzdZ1bm6PhygNTWrjvvxRVk7zHixfxEALWzAcmH5aeZp2XDWdf4ACv8aV9BuAE5jSpVeohg1x1AYyA6XUZySTd5ovSC7TbWXUm9nc6n8W0eHfjRGwDRoTiEwKzQxgXXwOpAiTh+PldoN//ZEiIcPfOGyKHBwapA=
