sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=mvsorg/mvs-explorer-api-v2
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$TAG .
    - docker push $REPO
env:
  global:
  - secure: vuMIw0qsVHxdt5mRiJHwJvcKYySA/5nSTEkXA3u0JhX6p8tCt8JlstvTYBlGC2+qDetaVtlCQZ/IZ7MbjbrkE0TKQZIwB4nediPX5cExk8+AYPlZY0N+kVLoC2pNEYXMX6/WaZ3a+YSbjq9Y2qFFikDHSmSNsUVCQB8G2/8IXIo6lBW4KswiEhj+iwE9wx7lU0IP9+J2//pcghhe5Qi8JxHyiI6EfP1ArKu24PwSEdyTZovnaShKMMuK3xUabii1n28LYP5p0D3/1kdTGZaW+kyJOcI6UdkQcyfzeSjgtAE4cyC09eBhk0IBG0DQaJhhh2or2riJ0U7518LxCs2whp0rShGSxtMMja9fNsbgP4bGtpTcy9ApgW/CRAFoeaS7HyTFTI1lfprDyjo4Nx1I98oobJga8dxIKm8OSJMB4V/hrRIMGR3w1t8PCL/HxwN0I1lCWgYusRPVpxyD9ALrkTY621dHoO3BiHtuDsTHLREReMOzBSl3nAGDaiCnC7EwshUe/yNGl1HyIsAt/Ak6TwXMP15U2VCdimVYHs8KEWAjPw0vD2NP7I1jwFtywUZB9TTIWUtvfGn0G/TMShizg7EFtQkr/rkfdA2zDdSvRQ+g6+zPheFYYBJxq+dXbBXw1gMCauiV0ro2apEbiKeMR2EKpsRPqcabFDOjCewYWW0=
  - secure: 1WnBB6p2Ff8l1TC+rjoTakGG2mJg/mbFKLOriiMXY8GA8dbtP3XXQLQ1TnCMtNciDR5QWphT/Zd5+HUur1AUckZse26rrKqWVm49CVOZzDqVWYk37JrJVD6n6H7l+zEkBIqF1EkJJaPkeFnR/vAaruA1skcQev32ma8CPYkjMa6llLo7kmHHSM1Lv2ZP56r7t5CV2izZow/KFsUnvV08WRlBcS0cZzfX1FfRoJAxdo9dn+qeKhmL/cfZqs1gLhnEr+3ui1XPczAkCyKLQJwtTISQJT4F/5BZ0ZRvz6wnij/56G225FyT5h2nZs7XcSBgygh0gW8FF8M6PIIFCPQI5CduMcG7/PVSvY21b/513CRtlfztSiOdVugK43yZfD/NjFnW4UVa3dkYUwYteKfvmJP3ib5WvMNGSv2SnlxeSVHQE4js/luaP1/j7g6Z6nWkWhD22c8PX5qI3SL/SsiXx98cVge7S7G7H/kaBO5ty2V3rtTdPkahyo9BxkSxthiNNNuBVwu/aCdFvy89WwzJ9n1pe+Eppn1e8wD5EOQNnSVudFTs1fmWaADmY8uaHnAJtA2Tt7DhV7ms/TrimFTLjBO9U9Q7Mm5RGp8+AXy4PC2/3YjR5cB1v9Enutpo+wxhMK8fDIQZpb0WBedqNNftmV+4PET3fZCmC9gJhFYyw5Q=
